import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PaperBackground from "./components/PaperBackground";
import localFont from "next/font/local";

const sansCulottes = localFont({
  src: "/fonts/SansCulottes/SansCulottes.ttf",
  variable: "--font-culot",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tipidicuts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sansCulottes.variable} antialiased`}
      >
        {children}
        <div className="bg-wrapper -z-1 top-0 left-0 fixed h-dvh w-dvw">
          <PaperBackground />
        </div>
      </body>
    </html>
  );
}
